<?php
/**
 * Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'BLOCK_FLEX_GRID_EDITOR_JS', 'editor.js' );
define( 'BLOCK_FLEX_GRID_FRONTEND_JS', 'frontend.js' );
define( 'BLOCK_FLEX_GRID_EDITOR_CSS', 'editor.css' );
define( 'BLOCK_FLEX_GRID_FRONTEND_CSS', 'frontend.css' );

define( 'BLOCK_FLEX_GRID_VERSION', '0.0.1' );
